image: python:3.12-slim

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache
    - venv/

test:
  stage: test
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pytest

deploy:
  stage: deploy
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - gunicorn app:app -b 0.0.0.0:5000
  only:
    - main 